#!/bin/bash

#
# Copyright (C) 2016 nCrux
# Released under the terms of the GNU GPL v2.0.
# Author: Aditi <aditi@ncrux.com>
#

usage() {
	man -P cat ncrux-config
}


if [ "$1" == "" ]; then
	usage
	exit 0
fi

if [ "$2" == "" ]; then
	echo Please provide configuration file name
	echo See \"man ncrux-config\" for more details
	exit 1 
else
	NCONFIG_FILE=$2
fi 

export PATH=/usr/lib/ncrux/ncrux-config:$PATH

CMD=$1

case "$CMD" in
menu|menu-n|menu-g|menu-q)
	if [ "$3" == "" ]; then
		NCONFIG_SRC=Nconfig
	else
		NCONFIG_SRC=$3
	fi 

	if [ ! -f $NCONFIG_SRC ]; then
		echo Source file $NCONFIG_SRC is not present
		exit 1
	fi

	export CONFIG_=NCONFIG_
	export KCONFIG_CONFIG=$NCONFIG_FILE
	;;
gen)
	if [ ! -f $NCONFIG_FILE ]; then
		echo Configuration file $NCONFIG_FILE is not present
		exit 1
	fi

	if [ "$3" == "" ]; then
		echo Please provide output file name
		exit 1
	else
		OUTPUT_FILE=$3
	fi 

	# Check output generator is available for requested file extension
	EXT=${OUTPUT_FILE##*.}
	;;
merge)
	if [ ! -f $NCONFIG_FILE ]; then
		echo Configuration file $NCONFIG_FILE is not present
		exit 1
	fi

	if [ "$3" == "" ]; then
		echo Please provide configuration fragment file
		exit 1
	else
		NCONFIG_FRAMENT=$3
	fi 

	if [ ! -f $NCONFIG_FRAMENT ]; then
		echo Configuration fragment file $NCONFIG_FRAMENT is not present
		exit 1
	fi
	;;
*)
	usage
	exit 1
esac


case "$CMD" in
menu)
	ncrux-mconf -s $NCONFIG_SRC
	;;
menu-n)
	ncrux-nconf $NCONFIG_SRC
	;;
menu-g)
	export NCRUX_CONFIG_GLADE_FILE=/usr/share/ncrux-config/ncrux-gconf.glade
	ncrux-gconf $NCONFIG_SRC
	;;
menu-q)
	ncrux-qconf $NCONFIG_SRC
	;;
gen)
	ncrux-config-gen-$EXT $NCONFIG_FILE $OUTPUT_FILE
	;;
merge)
	ncrux-config-merge $NCONFIG_FILE $NCONFIG_FRAMENT
	;;
esac

